- name: Configure Google Cloud credentials for Docker.
  hosts: vm_inv
  become: True
  tasks:
    - name: Configure gcloud credentials for Docker
      command: gcloud auth configure-docker europe-west4-docker.pkg.dev --quiet
      register: gcloud_auth
      changed_when: false

    - debug:
        var: compose_version.stdout
